use_frameworks!

platform :ios, '8.0'

target 'CMCollectionFlowLayouts_Example' do
  pod 'CMCollectionFlowLayouts', :path => '../'

  target 'CMCollectionFlowLayouts_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
